export enum UserRole {
  ADMIN = 'ADMIN',
  EASYCOIN = 'EASYCOIN',
  OWNER = 'OWNER',
  INVESTOR = 'INVESTOR',
  AUDITOR = 'AUDITOR',
  PAYMENT_VERIFIER = 'PAYMENT_VERIFIER',
  LEGAL_ADMIN = 'LEGAL_ADMIN',
}
